# A docker-compose must always start with the version tag. "3" is the latest version at this time.
version: "3"
# Use the keyword 'services' to start to define services.
services:          # 1 service = 1 container.
  d4XX:
    build:
        context: .
        dockerfile: Dockerfile
        args:
          ROS_DISTRO: humble
    image: "realsense_ros_docker:latest"       # image name with the version
    #container_name: Realsense_Camera_d435
    environment:
      DISPLAY: $DISPLAY
      PATH: $PATH
      NVIDIA_DRIVER_CAPABILITIES: all
      QT_X11_NO_MITSHM: 1
      ROS_DOMAIN_ID: $ROS_DOMAIN_ID
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - /dev/bus/usb:/dev/bus/usb
      - ./realsense_d4XX_cam.sh:/home/realsense_d4XX_cam.sh
    device_cgroup_rules:
      - 'c 189:* rmw'
      - 'c 81:* rmw'
    network_mode: "host"
    privileged: true
    tty: true
    command:
      - bash
      - /home/realsense_d4XX_cam.sh
      - "${D4XX_SN}"
      - "${D4XX_NAME}"
      - "${D4XX_WIDTH}"
      - "${D4XX_HEIGHT}"
      - "${POINT_CLOUD}"
      - "${IMU}"

  d405:
    build:
        context: .
        dockerfile: Dockerfile
        args:
          ROS_DISTRO: humble
    image: "realsense_ros_docker:latest"       # image name with the version
    #container_name: Realsense_Camera_d405
    environment:
      DISPLAY: $DISPLAY
      PATH: $PATH
      NVIDIA_DRIVER_CAPABILITIES: all
      QT_X11_NO_MITSHM: 1
      ROS_DOMAIN_ID: $ROS_DOMAIN_ID
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - /dev/bus/usb:/dev/bus/usb
      - ./realsense_d405_cam.sh:/home/realsense_d405_cam.sh
    device_cgroup_rules:
      - 'c 189:* rmw'
      - 'c 81:* rmw'
    network_mode: "host"
    privileged: true
    tty: true
    command:
      - bash
      - /home/realsense_d405_cam.sh
      - "${D405_SN}"
      - "${D405_NAME}"
      - "${D405_WIDTH}"
      - "${D405_HEIGHT}"

  enumerate_devices:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
    image: "realsense_ros_docker:latest"       # image name with the version
    container_name: Realsense_enumerate_devices
    environment:
      DISPLAY: $DISPLAY
      PATH: $PATH
      NVIDIA_DRIVER_CAPABILITIES: all
      QT_X11_NO_MITSHM: 1
      ROS_DOMAIN_ID: $ROS_DOMAIN_ID
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - /dev/bus/usb:/dev/bus/usb
    device_cgroup_rules:
      - 'c 189:* rmw'
      - 'c 81:* rmw'
    network_mode: "host"
    privileged: true
    tty: true
    command: rs-enumerate-devices

  realsense_viewer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
    image: "realsense_ros_docker:latest"
    container_name: Realsense_viewer
    environment:
      DISPLAY: $DISPLAY
      PATH: $PATH
      NVIDIA_DRIVER_CAPABILITIES: all
      QT_X11_NO_MITSHM: 1
      ROS_DOMAIN_ID: $ROS_DOMAIN_ID
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - /dev/bus/usb:/dev/bus/usb
    device_cgroup_rules:
      - 'c 189:* rmw'
      - 'c 81:* rmw'
    network_mode: "host"
    privileged: true
    tty: true
    command: realsense-viewer

  rviz:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
    image: "realsense_ros_docker:latest"       # image name with the version
    container_name: RViz
    env_file: .ros_env
    environment:
      DISPLAY: $DISPLAY
      PATH: $PATH
      NVIDIA_DRIVER_CAPABILITIES: all
      QT_X11_NO_MITSHM: 1
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    network_mode: "host"
    privileged: true
    tty: true
    command: bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && ros2 run rviz2 rviz2"

  rgbd_collector:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
    image: "realsense_ros_docker:latest"
    container_name: RGBD_collector
    env_file: .ros_env
    environment:
      DISPLAY: $DISPLAY
      PATH: $PATH
      NVIDIA_DRIVER_CAPABILITIES: all
      QT_X11_NO_MITSHM: 1
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    network_mode: "host"
    privileged: true
    tty: true
    volumes:
      - ./rgbd_collector.py:/home/rgbd_collector.py
      - ./rosbags:/home/rosbags
    depends_on:
      - d4XX
    command: bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && python3 /home/rgbd_collector.py"

  enter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
    image: "realsense_ros_docker:latest"
    container_name: Realsense_enter
    env_file: .ros_env
    environment:
      DISPLAY: $DISPLAY
      PATH: $PATH
      NVIDIA_DRIVER_CAPABILITIES: all
      QT_X11_NO_MITSHM: 1
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - /dev/bus/usb:/dev/bus/usb
      - ./rosbags:/home/rosbags
    network_mode: "host"
    privileged: true
    tty: true
    stdin_open: true
    command: bash
